version: '3.6'

services:
  mongo:
    image: ind3x/rpi-mongo-express
    container_name: rb-tracker__mongodb
    environment:
      - MONGO_INITDB_DATABASE=rb-tracker
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    volumes:
      - ./mongo/entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfigdb:/data/configdb
    ports:
      - 27017:27017
    networks:
      - rb-tracker__network
    command: mongod --port 27017

volumes:
  mongodb:
  mongoconfigdb:

networks:
  rb-tracker__network:
    driver: bridge
    name: rb-tracker__network




