version: '3.6'

services:
  mongo:
    image: ind3x/rpi-mongo-express
    container_name: rb-tracker__mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=192.168.178.50
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=rb-tracker
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=user

    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
    name: rb-tracker__network
